framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        name: SULUSESSID
    php_errors:
        log: true
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/website/manifest.json'
